export const values = {
  regina: 'regina',
  anton: 'anton',
  alisa: 'alisa',
  nadya: 'nadya',
  volodya: 'volodya',
  olya: 'olya'
};

export const map = {
  q1: {
    v1: values.regina,
    v2: values.anton,
    v3: values.volodya,
    v4: values.alisa,
    v5: values.nadya,
    v6: values.olya,
  },
  q2: {
    v1: values.regina,
    v2: values.nadya,
    v3: values.olya,
    v4: values.anton,
    v5: values.alisa,
    v6: values.volodya,
  },
  q3: {
    v1: values.alisa,
    v2: values.nadya,
    v3: values.anton,
    v4: values.regina,
    v5: values.olya,
    v6: values.volodya,
  },
  q4: {
    v1: values.nadya,
    v2: values.volodya,
    v3: values.anton,
    v4: values.alisa,
    v5: values.regina,
    v6: values.olya,
  },
  q5: {
    v1: values.olya,
    v2: values.alisa,
    v3: values.regina,
    v4: values.anton,
    v5: values.nadya,
    v6: values.volodya,
  },
  q6: {
    v1: values.anton,
    v2: values.regina,
    v3: values.alisa,
    v4: values.nadya,
    v5: values.volodya,
    v6: values.olya,
  },
  q7: {
    v1: values.olya,
    v2: values.anton,
    v3: values.alisa,
    v4: values.volodya,
    v5: values.nadya,
    v6: values.regina,
  },
  q8: {
    v1: values.volodya,
    v2: values.olya,
    v3: values.nadya,
    v4: values.regina,
    v5: values.anton,
    v6: values.alisa,
  },
  q9: {
    v1: values.regina,
    v2: values.volodya,
    v3: values.olya,
    v4: values.alisa,
    v5: values.nadya,
    v6: values.anton,
  },
  q10: {
    v1: values.olya,
    v2: values.alisa,
    v3: values.regina,
    v4: values.anton,
    v5: values.nadya,
    v6: values.volodya,
  },
  q11: {
    v1: values.olya,
    v2: values.regina,
    v3: values.alisa,
    v4: values.volodya,
    v5: values.nadya,
    v6: values.anton,
  },
  q12: {
    v1: values.nadya,
    v2: values.volodya,
    v3: values.anton,
    v4: values.alisa,
    v5: values.regina,
    v6: values.olya,
  },
  q13: {
    v1: values.regina,
    v2: values.nadya,
    v3: values.olya,
    v4: values.anton,
    v5: values.alisa,
    v6: values.volodya,
  },
}